### ISSUE TITLE
make run crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-tui#2]
on my mac, fresh repo, 

```make run```
----
```
mkdir -p bin
GO111MODULE=on go build -o bin/harmony-tui -v -ldflags="-X main.version=v19 -X main.commit=bb53fc4 -X main.builtAt=2019-10-11T10:25:08-0700 -X main.builtBy=leochen@harmony.one"  main.go
./bin/harmony-tui
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x42e1dfa]

goroutine 21 [running]:
github.com/harmony-one/harmony-tui/src.GetLogFilePath.func1(0xc0001e4040, 0x3d, 0x0, 0x0, 0x4445400, 0xc000098150, 0x0, 0x0)
        /Users/leochen/work/go/src/github.com/harmony-one/harmony-tui/src/logReader.go:81 +0x4a
path/filepath.Walk(0xc0001e4040, 0x3d, 0xc00004de10, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:402 +0x6a
github.com/harmony-one/harmony-tui/src.GetLogFilePath(0x43ccc2f, 0x7, 0x0, 0x0)
        /Users/leochen/work/go/src/github.com/harmony-one/harmony-tui/src/logReader.go:79 +0xaa
github.com/harmony-one/harmony-tui/src.TailZeroLogFile()
        /Users/leochen/work/go/src/github.com/harmony-one/harmony-tui/src/logReader.go:18 +0x4b
created by main.main
        /Users/leochen/work/go/src/github.com/harmony-one/harmony-tui/main.go:44 +0x35c
make: *** [run] Error 2
```

**Comment by LeoHChen** [comment]
<img width="1275" alt="Screen Shot 2019-10-11 at 11 49 36 AM" src="https://user-images.githubusercontent.com/4513927/66676831-3d68dd00-ec1d-11e9-8d05-f72045a19a24.png">

Runs on my linux box, and got the crash as well.  The program should detect the error and print out the error message instead of panic.
