### ISSUE TITLE
tui crash on real foundation node of mainnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-tui#8]
The TUI program runs for a few minutes and crash on a real foundational node of mainnet.

```
[ec2-user@ip-172-31-10-45 ~]$
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:350 +0x11f
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0000e04d0)
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:311 +0x594
created by github.com/hpcloud/tail.TailFile
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:133 +0x162

goroutine 65 [select]:
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc0000a4100)
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:236 +0x193
created by github.com/hpcloud/tail/watch.glob..func1
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:54 +0x12c

goroutine 66 [syscall]:
syscall.Syscall6(0xe8, 0xe, 0xc00043bd14, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x2, 0x2000000000020, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0xe, 0xc00043bd14, 0x7, 0x7, 0xffffffffffffffff, 0xc000284048, 0xc00043bdf4, 0xc000478300)
        /home/ec2-user/go/pkg/mod/golang.org/x/sys@v0.0.0-20190801041406-cbf593c0f2f3/unix/zsyscall_linux_amd64.go:1760 +0x72
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc0004b4220, 0xc00043bd00, 0x2, 0x0)
        /home/ec2-user/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify_poller.go:86 +0x91
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc00031e050)
        /home/ec2-user/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify.go:192 +0x18a
created by gopkg.in/fsnotify%2ev1.NewWatcher
        /home/ec2-user/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify.go:59 +0x1a8

goroutine 67 [select]:
github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents.func1(0xc0001fc080, 0xc0000e0548, 0xc0001fc0e0)
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify.go:88 +0x153
created by github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents
        /home/ec2-user/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify.go:77 +0x169
```

**Comment by LeoHChen** [comment]
after latest update, it is better on TUI, but I still l got one crash with "negative offset" error.  The log files may change due to zerolog will gzip periodically, we need to handle the situation.
